version: '2'
volumes:
  app:
  db:
services:
  app:
    container_name: gitea-app
    restart: always
    image: gitea/gitea:latest
    network_mode: bridge
    volumes:
      - ./volumes/gitea_app:/data
    ports:
      - "10022:22"
      - "3000:3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=${GITEA_HOSTNAME}
